import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import SidebarSpacer from "./components/SidebarSpacer";
import { SidebarVisibleProvider } from "./components/SidebarContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider appearance={{ elements: { userButtonPopoverActionButton__manageAccount: "hidden" } }}>
      <html lang="en">
        <body>
          <SidebarVisibleProvider>
            <Sidebar />
            <SidebarSpacer>{children}</SidebarSpacer>
          </SidebarVisibleProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
